from __future__ import annotations
from typing import Dict, Tuple

from pkmn_type_enum import *

# source: https://bulbapedia.bulbagarden.net/wiki/Type/Type_chart#Generation_I
# tuple key is (<attack type>, <defending Pokemon type>)
damage_effectiveness_map: Dict[Tuple[PokemonType, PokemonType], float] = {
    # NORMAL
    (NORMAL, NORMAL): 1.0,
    (NORMAL, FIGHTING): 1.0,
    (NORMAL, FLYING): 1.0,
    (NORMAL, POISON): 1.0,
    (NORMAL, GROUND): 1.0,
    (NORMAL, ROCK): 0.5,
    (NORMAL, BUG): 1.0,
    (NORMAL, GHOST): 0.0,
    (NORMAL, FIRE): 1.0,
    (NORMAL, WATER): 1.0,
    (NORMAL, GRASS): 1.0,
    (NORMAL, ELECTRIC): 1.0,
    (NORMAL, PSYCHIC): 1.0,
    (NORMAL, ICE): 1.0,
    (NORMAL, DRAGON): 1.0,

    # FIGHTING
    (FIGHTING, NORMAL): 2.0,
    (FIGHTING, FIGHTING): 1.0,
    (FIGHTING, FLYING): 0.5,
    (FIGHTING, POISON): 0.5,
    (FIGHTING, GROUND): 1.0,
    (FIGHTING, ROCK): 2.0,
    (FIGHTING, BUG): 0.5,
    (FIGHTING, GHOST): 0.0,
    (FIGHTING, FIRE): 1.0,
    (FIGHTING, WATER): 1.0,
    (FIGHTING, GRASS): 1.0,
    (FIGHTING, ELECTRIC): 1.0,
    (FIGHTING, PSYCHIC): 0.5,
    (FIGHTING, ICE): 2.0,
    (FIGHTING, DRAGON): 1.0,

    # FLYING
    (FLYING, NORMAL): 1.0,
    (FLYING, FIGHTING): 2.0,
    (FLYING, FLYING): 1.0,
    (FLYING, POISON): 1.0,
    (FLYING, GROUND): 1.0,
    (FLYING, ROCK): 0.5,
    (FLYING, BUG): 2.0,
    (FLYING, GHOST): 1.0,
    (FLYING, FIRE): 1.0,
    (FLYING, WATER): 1.0,
    (FLYING, GRASS): 2.0,
    (FLYING, ELECTRIC): 0.5,
    (FLYING, PSYCHIC): 1.0,
    (FLYING, ICE): 1.0,
    (FLYING, DRAGON): 1.0,

    # POISON
    (POISON, NORMAL): 1.0,
    (POISON, FIGHTING): 1.0,
    (POISON, FLYING): 1.0,
    (POISON, POISON): 0.5,
    (POISON, GROUND): 0.5,
    (POISON, ROCK): 0.5,
    (POISON, BUG): 2.0,
    (POISON, GHOST): 0.5,
    (POISON, FIRE): 1.0,
    (POISON, WATER): 1.0,
    (POISON, GRASS): 2.0,
    (POISON, ELECTRIC): 1.0,
    (POISON, PSYCHIC): 1.0,
    (POISON, ICE): 1.0,
    (POISON, DRAGON): 1.0,

    # GROUND
    (GROUND, NORMAL): 1.0,
    (GROUND, FIGHTING): 1.0,
    (GROUND, FLYING): 0.0,
    (GROUND, POISON): 2.0,
    (GROUND, GROUND): 1.0,
    (GROUND, ROCK): 2.0,
    (GROUND, BUG): 0.5,
    (GROUND, GHOST): 1.0,
    (GROUND, FIRE): 2.0,
    (GROUND, WATER): 1.0,
    (GROUND, GRASS): 0.5,
    (GROUND, ELECTRIC): 2.0,
    (GROUND, PSYCHIC): 1.0,
    (GROUND, ICE): 1.0,
    (GROUND, DRAGON): 1.0,

    # ROCK
    (ROCK, NORMAL): 1.0,
    (ROCK, FIGHTING): 0.5,
    (ROCK, FLYING): 2.0,
    (ROCK, POISON): 1.0,
    (ROCK, GROUND): 0.5,
    (ROCK, ROCK): 1.0,
    (ROCK, BUG): 2.0,
    (ROCK, GHOST): 1.0,
    (ROCK, FIRE): 2.0,
    (ROCK, WATER): 1.0,
    (ROCK, GRASS): 1.0,
    (ROCK, ELECTRIC): 1.0,
    (ROCK, PSYCHIC): 1.0,
    (ROCK, ICE): 2.0,
    (ROCK, DRAGON): 1.0,

    # BUG
    (BUG, NORMAL): 1.0,
    (BUG, FIGHTING): 0.5,
    (BUG, FLYING): 0.5,
    (BUG, POISON): 2.0,
    (BUG, GROUND): 1.0,
    (BUG, ROCK): 1.0,
    (BUG, BUG): 1.0,
    (BUG, GHOST): 0.5,
    (BUG, FIRE): 0.5,
    (BUG, WATER): 1.0,
    (BUG, GRASS): 2.0,
    (BUG, ELECTRIC): 1.0,
    (BUG, PSYCHIC): 2.0,
    (BUG, ICE): 1.0,
    (BUG, DRAGON): 1.0,

    # GHOST
    (GHOST, NORMAL): 0.0,
    (GHOST, FIGHTING): 1.0,
    (GHOST, FLYING): 1.0,
    (GHOST, POISON): 1.0,
    (GHOST, GROUND): 1.0,
    (GHOST, ROCK): 1.0,
    (GHOST, BUG): 1.0,
    (GHOST, GHOST): 2.0,
    (GHOST, FIRE): 1.0,
    (GHOST, WATER): 1.0,
    (GHOST, GRASS): 1.0,
    (GHOST, ELECTRIC): 1.0,
    (GHOST, PSYCHIC): 0.0,
    (GHOST, ICE): 1.0,
    (GHOST, DRAGON): 1.0,

    # FIRE
    (FIRE, NORMAL): 1.0,
    (FIRE, FIGHTING): 1.0,
    (FIRE, FLYING): 1.0,
    (FIRE, POISON): 1.0,
    (FIRE, GROUND): 1.0,
    (FIRE, ROCK): 0.5,
    (FIRE, BUG): 2.0,
    (FIRE, GHOST): 1.0,
    (FIRE, FIRE): 0.5,
    (FIRE, WATER): 0.5,
    (FIRE, GRASS): 2.0,
    (FIRE, ELECTRIC): 1.0,
    (FIRE, PSYCHIC): 1.0,
    (FIRE, ICE): 2.0,
    (FIRE, DRAGON): 0.5,

    # WATER
    (WATER, NORMAL): 1.0,
    (WATER, FIGHTING): 1.0,
    (WATER, FLYING): 1.0,
    (WATER, POISON): 1.0,
    (WATER, GROUND): 2.0,
    (WATER, ROCK): 2.0,
    (WATER, BUG): 1.0,
    (WATER, GHOST): 1.0,
    (WATER, FIRE): 2.0,
    (WATER, WATER): 0.5,
    (WATER, GRASS): 0.5,
    (WATER, ELECTRIC): 1.0,
    (WATER, PSYCHIC): 1.0,
    (WATER, ICE): 1.0,
    (WATER, DRAGON): 0.5,

    # GRASS
    (GRASS, NORMAL): 1.0,
    (GRASS, FIGHTING): 1.0,
    (GRASS, FLYING): 0.5,
    (GRASS, POISON): 0.5,
    (GRASS, GROUND): 2.0,
    (GRASS, ROCK): 2.0,
    (GRASS, BUG): 0.5,
    (GRASS, GHOST): 1.0,
    (GRASS, FIRE): 0.5,
    (GRASS, WATER): 2.0,
    (GRASS, GRASS): 0.5,
    (GRASS, ELECTRIC): 1.0,
    (GRASS, PSYCHIC): 1.0,
    (GRASS, ICE): 1.0,
    (GRASS, DRAGON): 0.5,

    # ELECTRIC
    (ELECTRIC, NORMAL): 1.0,
    (ELECTRIC, FIGHTING): 1.0,
    (ELECTRIC, FLYING): 2.0,
    (ELECTRIC, POISON): 1.0,
    (ELECTRIC, GROUND): 0.0,
    (ELECTRIC, ROCK): 1.0,
    (ELECTRIC, BUG): 1.0,
    (ELECTRIC, GHOST): 1.0,
    (ELECTRIC, FIRE): 1.0,
    (ELECTRIC, WATER): 2.0,
    (ELECTRIC, GRASS): 0.5,
    (ELECTRIC, ELECTRIC): 0.5,
    (ELECTRIC, PSYCHIC): 1.0,
    (ELECTRIC, ICE): 1.0,
    (ELECTRIC, DRAGON): 0.5,

    # PSYCHIC
    (PSYCHIC, NORMAL): 1.0,
    (PSYCHIC, FIGHTING): 2.0,
    (PSYCHIC, FLYING): 1.0,
    (PSYCHIC, POISON): 2.0,
    (PSYCHIC, GROUND): 1.0,
    (PSYCHIC, ROCK): 1.0,
    (PSYCHIC, BUG): 1.0,
    (PSYCHIC, GHOST): 1.0,
    (PSYCHIC, FIRE): 1.0,
    (PSYCHIC, WATER): 1.0,
    (PSYCHIC, GRASS): 1.0,
    (PSYCHIC, ELECTRIC): 1.0,
    (PSYCHIC, PSYCHIC): 0.5,
    (PSYCHIC, ICE): 1.0,
    (PSYCHIC, DRAGON): 1.0,

    # ICE
    (ICE, NORMAL): 1.0,
    (ICE, FIGHTING): 1.0,
    (ICE, FLYING): 2.0,
    (ICE, POISON): 1.0,
    (ICE, GROUND): 2.0,
    (ICE, ROCK): 1.0,
    (ICE, BUG): 1.0,
    (ICE, GHOST): 1.0,
    (ICE, FIRE): 1.0,
    (ICE, WATER): 0.5,
    (ICE, GRASS): 2.0,
    (ICE, ELECTRIC): 1.0,
    (ICE, PSYCHIC): 1.0,
    (ICE, ICE): 0.5,
    (ICE, DRAGON): 2.0,

    # DRAGON
    (DRAGON, NORMAL): 1.0,
    (DRAGON, FIGHTING): 1.0,
    (DRAGON, FLYING): 1.0,
    (DRAGON, POISON): 1.0,
    (DRAGON, GROUND): 1.0,
    (DRAGON, ROCK): 1.0,
    (DRAGON, BUG): 1.0,
    (DRAGON, GHOST): 1.0,
    (DRAGON, FIRE): 1.0,
    (DRAGON, WATER): 1.0,
    (DRAGON, GRASS): 1.0,
    (DRAGON, ELECTRIC): 1.0,
    (DRAGON, PSYCHIC): 1.0,
    (DRAGON, ICE): 1.0,
    (DRAGON, DRAGON): 2.0,
}

def damage_effectiveness(attacking_type: PokemonType, defending_type: PokemonType) -> float:
    return damage_effectiveness_map[(attacking_type, defending_type)]
